[package]
name = "nes_ui_sfml"
version = "0.1.0"
authors = ["Amjad Alsharafi <amjadsharafi10@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plastic_core = { path = "../plastic_core" }

sfml = "^0.15.1"
