
[workspace]
resolver = "2"
members = [
    "plastic_core", "plastic_ui",
]
exclude = [
    "nes_ui_sfml", 
    "nes_ui_gtk",
    "nes_ui_tui",
    "nes_ui_native_windows",
]
default-members = ["plastic_ui"]

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3

