
[workspace]
resolver = "2"
members = [
    "nes_ui_sfml", 
    "nes_ui_gtk",
    "nes_ui_tui",
    "nes_ui_native_windows",
    "plastic_core",
]
default-members = ["nes_ui_sfml"]

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3

