[package]
name = "plastic"
version = "0.3.0"
edition = "2021"

[dependencies]
plastic_core = { path = "../plastic_core", version = "0.3.0" }
egui = "0.29"
egui-winit = "0.29"
directories = "5.0"
eframe = "0.29"
rfd = "0.15"
dynwave = "0.1"
